pipeline:
  build:
    image: vitalikpaprotsky/repeek-base:latest
    commands:
      - gem update bundler
      - bundle install
      - rspec spec

    environment:
      RACK_ENV: test
      RAILS_ENV: test
      MONGO_HOST_TEST: mongo
      MONGO_PORT_TEST: '27017'

  # When master branch is pushed to GitHub or some other branch is merged to it
  # Push repeek image to DockerHub with latest tag
  docker:
    image: plugins/docker
    email: vetalpaprotsky@gmail.com
    repo: vitalikpaprotsky/repeek
    tags: latest
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

  # When a new tag is created on GitHub
  # Push repeek image to DockerHub with GitHub tag
  docker:
    image: plugins/docker
    email: vetalpaprotsky@gmail.com
    repo: vitalikpaprotsky/repeek
    tags: ${DRONE_TAG}
    secrets: [ docker_username, docker_password ]
    when:
      event: tag

  # When a new tag is created on GitHub
  # Deploy repeek image to Rancher with GitHub tag
  rancher:
    image: peloton/drone-rancher
    url: ${RANCHER_URL}
    access_key: ${RANCHER_ACCESS_KEY}
    secret_key: ${RANCHER_SECRET_KEY}
    service: repeek/web
    docker_image: "vitalikpaprotsky/repeek:${DRONE_TAG}"
    when:
      event: tag

services:
  mongo:
    image: mongo:3.4.5
