version: '2'
services:
  mongo:
    image: mongo:3.4.5
    volumes:
    - /docker_volumes/mongo:/data/db
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: role=repeek-staging
  web:
    image: vitalikpaprotsky/repeek-staging:latest
    environment:
      RACK_ENV: staging
      RAILS_ENV: staging
      PORT: '3000'
      MONGO_HOST_STAGING: mongo
      MONGO_PORT_STAGING: '27017'
      REPEEK_MAILER_PASSWORD: repeek123
    links:
    - mongo:mongo
    command:
    - bin/rails
    - s
    labels:
      io.rancher.container.pull_image: always
  lb:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
