version: '2'
services:
  mongo:
    image: mongo:3.4.5
    volumes:
    - /docker_volumes/mongo:/data/db
    labels:
      io.rancher.scheduler.affinity:host_label: role=repeek-staging
      io.rancher.container.pull_image: always
  web:
    image: vitalikpaprotsky/repeek:latest
    environment:
      MONGO_HOST_STAGING: mongo
      MONGO_PORT_STAGING: '27017'
      PORT: '3000'
      RACK_ENV: staging
      RAILS_ENV: staging
      REPEEK_MAILER_PASSWORD: repeek123
    links:
    - mongo:mongo
    command:
    - sh
    - .staging-start.sh
    labels:
      io.rancher.scheduler.affinity:host_label: role=repeek-staging
      stack: repeek
      io.rancher.container.pull_image: always
      service: web
  lb:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
