version: '2'
services:
  mongo:
    scale: 1
    start_on_create: true
  web:
    scale: 1
    start_on_create: true
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: 138.68.98.232
        path: ''
        priority: 1
        protocol: http
        service: web
        source_port: 80
        target_port: 3000
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
